### PR TITLE
Support gnome 3.32

### PR DESCRIPTION
**Pull request by ccat3z**
Gnome 3.32 doesn't support Lang.Class anymore. https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/361

### CODE REVIEW

**Comment by ccat3z** [comment]
#75

**Comment by philgood** [comment]
Any chance this Pull Request can be approved? I have argos scripts that have stopped working.

**Comment by ccat3z** [comment]
@philgood Any example?
this commit replace Lang.Class with ES6 class. Is should work on gnome 3.32

**Comment by ccat3z** [comment]
@philgood Any example?
this commit replace Lang.Class with ES6 class. Is should work on gnome 3.32

**Comment by philgood** [comment]
I run a cpu load script using ps and stopped running every 5s. I cloned your fork and is now working well. Thank you @ccat3z

**Comment by prurigro** [comment]
This fork fixes everything I've tested except base64 icons. Thanks!

**Comment by p-e-w** [comment]
Thanks for looking into this! Two questions:

1. What about the other uses of `Lang.Class`? Do they not have to be replaced as well?
2. Argos is currently compatible with all GNOME Shell versions since 3.14 (well, except the latest one :smirk:). Will it still work with 3.14 after this change?

**Comment by jaromero** [comment]
`load_gicon()` In lineview.js#58 now takes 5 arguments instead of 4, and the last argument is a scale float (I think [these](https://developer.gnome.org/st/stable/st-st-texture-cache.html#st-texture-cache-load-gicon) are the relevant docs? How do people even find these things in the first place?).

Locally I've set it to 1.0 and I've got my b64 icons back for now, but I'm not sure what the proper solution for this is.

**Comment by ccat3z** [comment]
> 1. What about the other uses of `Lang.Class`? Do they not have to be replaced as well?

Lang.Class classes extends GObject still work well. These class use a metaclass.

For more detail:

1. https://ptomato.wordpress.com/2017/07/14/inventing-gobject-es6-classes/
2. https://gitlab.gnome.org/GNOME/gnome-shell/blob/master/HACKING.md#classes 

> 2. Argos is currently compatible with all GNOME Shell versions since 3.14 (well, except the latest one smirk). Will it still work with 3.14 after this change?

for api change of st_texture_cache_load_gicon maybe not work before 3.32
for ES6 class maybe not work before 3.26
need more test

**Comment by zeten30** [comment]
I can confirm that it works in Gnome 3.32. Good job :+1:

**Comment by cklosowski** [comment]
I can confirm this fixed my issues with having nested menus.

It did actually also fix my base64 encoded images as well. While some display issues exist, I think this PR overall fixes the issues with menus break.

Nice work @ccat3z

**Comment by p-e-w** [comment]
Thanks to everyone who has tested this and confirmed it works. Unfortunately, this PR breaks compatibility with all GNOME releases *except* 3.32, so it cannot be merged in its current form.

We need a solution that works for 3.32 while maintaining compatibility with a reasonable number of older versions. A year ago there were still quite a few people on GNOME 3.14, but supporting only 3.20 and newer would probably be fine.

**Comment by zeten30** [comment]
Sure, this breaks backwards compatibility. What about starting separate (github) branch/tag and uploading it as new extension ('argos2' for example) to extensions.gnome.org so users can easily pick their desired extension version?

**Comment by cklosowski** [comment]
I'm not sure what the 'Shell Version' Dropdown does on the extensions listing, but is that something you could use to deliver a different version of the package depending on what Shell Version the user is on?

**Comment by p-e-w** [comment]
To be clear, there will not be an "argos2" (or similar) secondary extension for 3.32, as that would create a maintenance nightmare and be bound to introduce confusion for users.

So there are two options:

1. Have code that runs on 3.32 while maintaining backwards compatibility (preferred)
2. Have a way to deliver a different version of the extension for different GNOME Shell versions using the same extension name (as indicated by @cklosowski)

Nothing in the (sparse) documentation provided by GNOME clearly indicates that option 2 is possible, though I would love to be proven wrong here.

The main issue is that for now, the userbase of GNOME versions *other than* 3.32 still dwarfs that of 3.32 itself. Therefore, any change that degrades the experience of pre-3.32 users in any way is an automatic non-starter.

**Comment by cklosowski** [comment]
Maybe @micheleg (developer of Dash to Dock) has an idea how the `shell-version` information in the `metadata.json` works for the developers benefit. It appears that the project is using the metadata to handle this.

**Comment by ccat3z** [comment]
It seems that old version is avaliable for pre-3.32 users.
v

**Comment by p-e-w** [comment]
Indeed, this is what other extension authors seem to be doing as well, so this is good to go. I have merged the PR and submitted an update to extensions.gnome.org.

Thanks again to everyone who helped test this, and of course most of all to @ccat3z for submitting this PR!

**Comment by cklosowski** [comment]
Thank you @ccat3z and @p-e-w .

**Pull request merged**
