### PR TITLE
README: Update installation section

### PR DESCRIPTION
**Pull request by mwilck**
@p-e-w: Please check if this is ok for you.

### CODE REVIEW

**Comment by tanrax** [comment]
Why is it no longer supported in version 46 with extensions.gnome.org?

**Comment by mwilck** [comment]
It hasn't been supported on e.g.o for a long time. See #108.

@p-e-w, the current README is misleading. But the README is the main entry point to argos, and argos is still your project, thus I've been waiting for your thumbs-up-or-down. I'll wait some more, but I reckon that sooner or later this should be merged in order to avoid confusing people.

**Comment by BANOnotIT** [comment]
@mwilck I spend like two hours trying to understand if there is any possibility for me to even install the thing. Neither #108, nor anything else says you should go into this PR and check instructions here

It's too much time wasted already on even personal level, and I don't know how many people spend or even haven't reached this PR.

As an outsider I don't understand why this PR is still not merged. That would save me so much time.

**Comment by mwilck** [comment]
I guess you're right, @p-e-w hasn't objected for 4 months.
Merging.

**Comment by mwilck** [comment]
> As an outsider I don't understand why this PR is still not merged.

The reason is simple. This is @p-e-w's project. I am just a random guy who jumped in very late and took care of some adaptations for newer GNOME releases. @p-e-w was generous enough to grant me the ability to merge stuff. I try to avoid abusing that. That means that I wait before merging anything.

The other reason is that I try to do this maintenance with minimal effort. I don't come here regularly to check, and it can happen that a few months pass by without anything happening.

If you're unhappy with that, go ahead and fork the project, create PRs, etc. It's open source, after all. 

It's understood that the situation is currently less than perfect for end users. But that's mostly due to ever-changing GNOME APIs and the issues we had with extensions.gnome.org.

**Pull request merged**
