### PR TITLE
Use registerClass to make plugin compatible with gnome 3.36.

### PR DESCRIPTION
**Pull request by rammie**
I realize that there is some sort of maintenance vacuum with this project (as an aside, appreciate the detailed notice - https://github.com/p-e-w/argos/issues/108#issuecomment-585076628, and feel similarly). That said, this PR fixes the compatibility with 3.36 for me, so I figured I'd submit it anyway. It might be useful to someone even if it doesn't get merged. I'm not sure if this breaks Argos on older versions of gnome.

Refs #105

### CODE REVIEW

**Comment by p-e-w** [comment]
Thanks for the fix, but this will likely break Argos on all GNOME Shell versions before 3.36, which most people aren't using yet. Once that changes, I intend to merge this PR.

**Comment by LaurentOngaro** [comment]
Thanks for the fix too, it made Argos runs again on my system (3.36 version of Gnome Shell)

**Comment by vltr** [comment]
Confirmed working on Arch with Gnome 3.36 (at least to the extent of my usage).

**Comment by pieplu** [comment]
It may be naive, but it is not possible, depending on the version of gnome, to use or not `GoObject.registerClass`. The javascript class looks exactly the same.

**Comment by javadr** [comment]
Thanks a lot. It fixed my problem with Gnome 3.36 on manjaro.

**Comment by Borromini** [comment]
Same here, thanks for the fix, Argos works again now on Debian Testing (a hodgepodge of GNOME 3.34 and 3.36 packages at the moment).

**Comment by mwilck** [comment]
> It may be naive, but it is not possible, depending on the version of gnome, to use or not `GoObject.registerClass`? The javascript class looks exactly the same.

If it was possible at all (I doubt it), it messes up the code a lot. It's much easier to create branches for the various GNOME shell releases and upload separate versions to extensions.gnome.org, which supports this just fine.

**Comment by ztane** [comment]
Why is it necessary to change everything? Doesn't it just need a `registerClass` there, *after* the class body?

**Comment by mwilck** [comment]
@ztane, why don't you try and report results?

**Comment by pieplu** [comment]
> If it was possible at all (I doubt it)

It's looks like simple to do the check : https://stackoverflow.com/questions/34120963/how-can-my-gnome-shell-extension-detect-the-gnome-version

But I did not see the change line 31, and your right, It messes up the code.

**Comment by mwilck** [comment]
@pieplu, I didn't mean obtaining the version was impossible. I doubt that it's possible to write conditional code that works for the ES6 classes. @ztane's idea might be worth a closer look. 
I personally wouldn't do this, and rather create branches.

**Comment by ztane** [comment]
@mwilck because I do not have that Gnome Shell version *yet*.

**Comment by mwilck** [comment]
@ztane, ok, I'll see if I can give it a quick shot here.

**Comment by mwilck** [comment]
@ztane and all,

I've had another look and it seems that, at least for the relatively simple classes that argos uses, it would be possible to enable GNOME 3.36 support in a backward-compatible way. I have a version of argos here that runs unmodified on 3.26, 3.34, and 3.36, and would probably also support older releases. It still needs some cleanup though.

**Comment by mwilck** [comment]
The argos code that supports GNOME 3.26-3.36 can be inspected [here](https://github.com/mwilck/argos/pull/1) now. It's just in my forked argos repo for now.

I've deliberately not created a PR for the `p-e-w/argos` repo, because I don't want it to look as if I wanted to take anything of @rammie's merits. However, @rammie, if you're ok with this code, and others agree, too, I'd of course create a PR here.

**Comment by insign** [comment]
@mwilck idk exactly why but @rammie's worked for me, yours not. But thanks both.

**Comment by mwilck** [comment]
@insign, could you be more specific please? What fails, exactly? Are the Argos buttons not visible at all, or are they misbehaving in some way? Which GNOME version, what distro? Can you provide `journalctl --user`  logs, and perhaps specific argos scripts you're using? Could you test with a trivial script, something like below, and see if that works?

     cat >~/.config/argos/test.sh <<EOF
     #! /bin/bash
     echo hello
     echo world
     EOF
     chmod 0755 ~/.config/argos/test.sh

**Comment by LaurentOngaro** [comment]
@mwilck , can you tell me what gnome version are using to develop and test ?

**Comment by mwilck** [comment]
@LaurentOngaro, I've been using 3.36.1, 3.34.5, and 3.26.

**Comment by LaurentOngaro** [comment]
OK, I see, I don't think the code will work on 3.36.2+ without major code changes
more info [here ](https://github.com/p-e-w/argos/issues/116#issue-611343488)

**Comment by mwilck** [comment]
Meanwhile, I figured that the `color=` text attribute doesn't work (i.e. has no effect) under 3.36. I guess it's a pango problem. Other attributes like `font=` and `size=` work.

**Comment by LaurentOngaro** [comment]
@mwilck , `color` is working for me on 3.36.2 with your last repository code

**Comment by mwilck** [comment]
@insign?

**Comment by joshp23** [comment]
@rammie thank you for the fix!

**Comment by mgajda** [comment]
Thanks a lot!
It works for me on Gnome 3.36 and Ubuntu.
Would it possible to upload 3.36 support to https://extensions.gnome.org?

**Comment by leoherzog** [comment]
What's the status of this PR and/or the backwards-compatible version by @mwilck? Debian Testing is using `gnome-shell` 3.38 and Ubuntu 20.04 (almost a year old) is on `gnome-shell` 3.36.4, both of which are broken without these fixes.

**Comment by michel-slm** [comment]
Since we use Argos at work, I had to package a patched version in Fedora because Fedora 33 used Gnome 3.38:
https://src.fedoraproject.org/rpms/gnome-shell-extension-argos

of course, that's now broken again for the upcoming Fedora 34 as it uses GNOME 40. I'm a bit concerned by the lack of activity on this issue...

**Comment by mwilck** [comment]
You can just use my code. I'm using it here under GNOME 3.38.3

**Comment by bstin** [comment]
@mwilck / @rammie  Thanks for both of your help over the last year or so in maintaining this project....

Are there any plans to support Gnome 40? Or are the changes too big to be worth it? 

Just trying to gauge how quickly I should move to 40 since I depend on argos for day to day task....

**Comment by mwilck** [comment]
I don't test with GNOME beta versions. So if anyone has time to test my latest code with GNOME 40, I'd be grateful. I don't even follow GNOME development closely - is there reason to suspect that there will be even more compatibility issues than usual? GNOME 3.36 -> 3.38 was almost too smooth to believe it.

**Comment by bstin** [comment]
@mwilck 
So I got some time today to test and preliminary results looks good!

I just manually changed metadata.json to read:

```
{
  "uuid": "argos@pew.worldwidemann.com",
  "name": "Argos",
  "description": "Create GNOME Shell extensions in seconds",
  "url": "https://github.com/p-e-w/argos",
  "version": 4,
  "shell-version": ["40"]
}
```
and seems to load without issue. No colors, but thats of minor importance to me. Granted, my script is very simple and only outputs information, its not interactive. 

Hopefully someone chimes in that uses a more complex script....but basic use case looks like it works.

**Comment by mwilck** [comment]
@bstin, good to know! The complexity of the script doesn't matter much, rather the use of the menu rendering options that argos offers (see README.md).

**Comment by p-e-w** [comment]
Ok folks, what do you want me to do here? There is this PR and there is also https://github.com/mwilck/argos/pull/1, which hasn't been opened as an upstream PR yet. Which of them works on which GNOME Shell versions? The information is all over the place ATM.

Please note that as stated previously, **I do not use GNOME Shell anymore.** Therefore, my motivation to keep Argos working is quite slim, especially since GNOME appears to be continuing its "policy" of breaking Shell extensions on every release every six months, so most maintenance work is just scrambling to keep up with the insane pace of upstream breakage.

I am also reiterating my offer to grant write access to this repo to someone interested in maintaining Argos going forward. If you can see yourself filling that role, **please announce yourself.**

**Comment by dvogel** [comment]
FWIW @mwilck's changes are working for me on Ubuntu 20 w/ gnome-shell 3.36.7

**Comment by mwilck** [comment]
I'm creating a PR for the main repo now: #127. @rammie didn't respond to my [question](https://github.com/p-e-w/argos/pull/111#issuecomment-623550510) above for more than a year, it appears he isn't interested any more. @insign hasn't provided further insight either, and I've received positive feedback and requests for a mainline PR from various people.

**Comment by fernando-stteffen** [comment]
that works for my thank you!

**Comment by p-e-w** [comment]
Superseded by #127.

**Pull request closed without merging**
